runtime: php74

entrypoint: serve --workers=15 public/index.php

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1
  max_concurrent_requests: 15

# You might want to create an override config.php and set webhook.max_connections to match max_concurrent_requests & --workers value

default_expiration: "1d"

handlers:
- url: /admin.*
  script: auto
  login: admin
  secure: always

- url: /.*
  script: auto
  secure: always

includes:
  - env_variables.yaml
