runtime: php74

entrypoint: serve public/index.php

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1

default_expiration: "1d"

handlers:
- url: /admin.*
  script: auto
  login: admin
  secure: always

- url: /.*
  script: auto
  secure: always

includes:
  - env_variables.yaml
